### ISSUE TITLE
2.0.1 --full-help, --build-help & --help not working

### ISSUE THREAD

**Issue by ElijahLynn** [ckeditor/ckbuilder#6]
I checked out ckeditor-dev repo and checked out tag 4.4.7. It has dev/builder/build.sh version 2.0.1.

When I run ./build.sh  with either --full-help, --build-help or --help it just ignores it and goes on building.

The version of build.sh 1.7.2 that comes in the tag 4.4.1 works fine with those options.

**Comment by adelura** [comment]
It has been fixed via #3 in [2.0.3](https://github.com/ckeditor/ckbuilder/releases/tag/2.0.3) version. You can use this builder version by changing its version in [build.sh](https://github.com/ckeditor/ckeditor-dev/blob/master/dev/builder/build.sh#L12) file. Since editor version 4.4.8, we are going to use recent builder. Hope it helps :).

**Comment by ElijahLynn** [comment]
Thank you
